version: '3'
services:
    web:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d

    app:
        build: ./app
        environment:
            TZ:              'Asia/Tokyo'
            PASTE_ID_LENGTH: '8'
            PB_APP_PORT:     '5000'
            PB_DB_HOST:      'mysql'
            PB_DB_PORT:      '3306'
            PB_DB_USER:      'root'
            PB_DB_PASSWORD:  'root'
            PB_DB_NAME:      'pastebin'
        command:
            - "sh"
            - "-c"
            - "pipenv sync && pipenv run gunicorn -w5 src:app -b :5000 --access-logfile=-"
        working_dir: /app
        volumes:
            - ./app:/app
            - virtualenvs:/root/.local/share/virtualenvs
        restart: always

    mysql:
        image: mysql:8.0
        environment:
            - "TZ=Asia/Tokyo"
            - "MYSQL_ROOT_PASSWORD=root"
        volumes:
            - mysql:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "13306:3306"
        restart: always

volumes:
    mysql:
    virtualenvs:
