version: '3'
services:
    web:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf

    app:
        build: ./app
        environment:
            - "TZ=Asia/Tokyo"
            - "PASTE_PATH=/pastes"
            - "PASTE_ID_LENGTH=8"
        command:
            - "sh"
            - "-c"
            - "pipenv sync && pipenv run gunicorn -w5 src:app -b :5000 --access-logfile=-"
        working_dir: /app
        volumes:
            - ./app:/app
            - pastes:/pastes

volumes:
    pastes:
